### ISSUE TITLE
release is doing wrong without release branch 0.3 and 0.4

### ISSUE THREAD

**Issue by haarchri** [crossplane-contrib/provider-kafka#55]
### What happened?

it looks like that the release is doing wrong without release branches for 0.3 and 0.4 this lead to the fact that marketplace version is only 0.2 
https://marketplace.upbound.io/providers/crossplane-contrib/provider-kafka/v0.2.0

### What environment did it happen in?
Crossplane version:

**Comment by hasheddan** [comment]
It looks like this is due to CI failing, which is now fixed in https://github.com/crossplane-contrib/provider-kafka/pull/52. @marshmallory we could either delete the tag and release and re-publish, or we could try rolling forward to the `v0.5.0`. I imagine no one is consuming `v0.4.0` since it failed to publish?

**Comment by marshmallory** [comment]
Actually, scratch that. I forgot to set it as the latest release.  v.0.4.1 should be released now and set as latest with the #52 bugfix.

**Comment by haarchri** [comment]
can we create a release-0.5 branch, tag v0.5.0 and rerun ci for release-0.5 branch - then the release will published aswell in marketplace

**Comment by marshmallory** [comment]
Fixed!  This was my misunderstanding about the release process.  Got it going forward :).  v0.4.2 is now available in marketplace.

**Comment by marshmallory** [comment]
Closing as release is fixed.
